### ISSUE TITLE
[Request] make the details of your project seem easier to understand / make flutter better

### ISSUE THREAD

**Issue by azkadev** [abdelaziz-mahdy/face_grouping#1]
currently machine learning / AI in Flutter is very low even if it exists it's not offline everything is connected to a 3rd party API, please add readme video demo, add tags + description

This is done to enable more people to be more interested in Flutter

Sorry, my English is bad

**Comment by abdelaziz-mahdy** [comment]
I will try to do so, no promises for now.

A readme and screenshots are easy 

And will try to separate the modules to be easier for people to understand 

Don't worry your English is good.

**Comment by abdelaziz-mahdy** [comment]
i think this can be closed now
